spring:
  cache:
    caffeine:
      spec: maximumSize = 1, expireAfterWrite = 10m
  data:
    redis:
      url: ${REDIS_URL}
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

resilience4j.ratelimiter:
  instances:
    githubApi:
      limit-for-period: 5
      limit-refresh-period: 1s
      timeout-duration: 500ms

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    com.Enigmazer.todo_app: INFO