package com.Enigmazer.todo_app.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents a category for organizing tasks in the todo application.
 * Categories can be either user-specific or global, and are used to group related tasks together.
 * Each category is associated with a user (unless it's a global category).
 */
@Entity
@Getter
@Setter
@Table(
        name = "category",
        indexes = @Index(name = "idx_user", columnList = "user_id")
)
public class Category {
    /**
     * Unique identifier for the category.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the category.
     * The Maximum length is 25 characters and cannot be null.
     */
    @Column(length = 25, nullable = false)
    private String name;

    /**
     * Flag indicating whether this category is global.
     * Global categories are available to all users.
     * Default value is false.
     */
    private boolean isGlobal = false;

    /**
     * The user who owns this category.
     * This field is ignored during JSON serialization to prevent circular references.
     * For global categories, this field may be null.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @JsonIgnore
    private User user;
}