package com.Enigmazer.todo_app.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

@Getter
@Setter
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Entity
@Table(name = "task")
public class Task {

    /**
     * Unique identifier for the task.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title or name of the task.
     * This is a required field and cannot be null.
     */
    @Column(nullable = false)
    private String title;

    /**
     * Detailed description of the task.
     * Stored as TEXT in the database to allow for longer descriptions.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * The date and time by which the task should be completed.
     * This is a required field and cannot be null.
     */
    @Column(nullable = false)
    private Instant dueDate;

    /**
     * Indicates whether the task has been marked as completed.
     * Defaults to false when a new task is created.
     */
    @Column(nullable = false, columnDefinition = "BOOLEAN DEFAULT FALSE")
    @Builder.Default
    private boolean isCompleted = false;

    /**
     * Flag to enable or disable email notifications for this task.
     * When enabled, the system can send reminders about upcoming or overdue tasks.
     */
    @Column(nullable = false, columnDefinition = "BOOLEAN DEFAULT FALSE")
    @Builder.Default
    private boolean isEmailEnabled = false;

    /**
     * Indicates whether a reminder for this task has been sent.
     * Used to prevent sending duplicate reminders.
     */
    @Column(nullable = false, columnDefinition = "BOOLEAN DEFAULT FALSE")
    @Builder.Default
    private boolean isReminderSent = false;

    /**
     * The timestamp when the task was created.
     * Automatically set when the task is first saved.
     */
    @Column(nullable = false)
    private Instant createdAt;

    /**
     * The timestamp when the task was last modified.
     * Automatically updated whenever the task is saved.
     */
    @Column(nullable = false)
    private Instant lastUpdatedAt;

    /**
     * The category to which this task belongs.
     * Tasks must be associated with a category.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    /**
     * The user who owns this task.
     * Tasks are private to the user who created them.
     * {@code @JsonIgnore} is used to prevent circular references during JSON serialization.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    /**
     * JPA lifecycle callback that is triggered before a new entity is persisted.
     * Sets the creation and last update timestamps to the current time.
     */
    @PrePersist
    public void onCreate(){
        this.createdAt = Instant.now();
        this.lastUpdatedAt = Instant.now();
    }

    /**
     * JPA lifecycle callback that is triggered before an entity is updated.
     * Updates the last update timestamp to the current time.
     */
    @PreUpdate
    public void onUpdate(){
        this.lastUpdatedAt = Instant.now();
    }
}
