package com.Enigmazer.todo_app.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;
import java.util.HashSet;
import java.util.Set;

/**
 * Represents a user in the todo application.
 * Users can be authenticated either through the local system or via OAuth providers.
 * Each user can have multiple tasks and categories associated with their account.
 */
@Entity
@Table(name = "users", uniqueConstraints
        = @UniqueConstraint(columnNames = {"provider", "providerId"}))
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class User {

    /**
     * Unique identifier for the user.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The full name of the user.
     * This is a required field and cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The email address of the user.
     * This must be unique across all users and cannot be null.
     */
    @Column(unique = true, nullable = false)
    private String email;

    /**
     * The hashed password of the user.
     * This field is nullable to support OAuth users who authenticate through third-party providers.
     * {@code @JsonIgnore} prevents the password hash from being included in JSON responses.
     */
    @Column(nullable = true)
    @JsonIgnore
    private String password;

    /**
     * The set of roles assigned to the user.
     * Roles are stored in a separate table and eagerly fetched to ensure they're available for authorization checks.
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"))
    @Column(nullable = false, name = "role")
    private Set<String> roles = new HashSet<>();

    /**
     * Indicates whether the user account is enabled.
     * Disabled accounts cannot log in to the system.
     */
    @Column(nullable = false)
    private boolean isEnabled = true;

    /**
     * The authentication provider used by the user.
     * Examples: "google", "github", "local" for local authentication.
     */
    @Column(nullable = false)
    private String provider;

    /**
     * The unique identifier provided by the OAuth provider.
     * This is used to associate the local user account with the external provider's account.
     * And it should be unique.
     */
    @Column(unique = true)
    private String providerId;

    /**
     * The timestamp when the user account was created.
     */
    @Column(nullable = false)
    private Instant createdAt;

    /**
     * The timestamp when the user account was last updated.
     */
    @Column(nullable = false)
    private Instant updatedAt;

    /**
     * The timestamp of the user's last successful login.
     */
    @Column(nullable = false)
    private Instant lastLogin;
    
    /**
     * JPA lifecycle callback that is triggered before a new user is persisted.
     * Initializes the timestamps for creation, update, and last login.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
        updatedAt = Instant.now();
        lastLogin = Instant.now();
    }

}

